#!/bin/sh
### BEGIN INIT INFO
# Provides:          gps-date
# Required-Start:    $remote_fs $syslog $network $gpsd
# Should-Start:      
# Required-Stop:     $remote_fs $syslog $network $gpsd
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Start-Before:    ntp
# Short-Description: GPS (Global Positioning System) Date Snapshot
# Description:       Grab the current date from GPS device before NTP syncs
#                   
### END INIT INFO

NAME=gps-date

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
. /lib/lsb/init-functions

echo -n "Acquiring date from GPS... "

GPSDATE=`gpspipe -w | head -10 | grep time | sed -r 's/.*"time":"([^"]*)".*/\1/' | head -1`
echo $GPSDATE
date -s $GPSDATE &> /dev/null
log_daemon_msg "Setting date from GPS $GPSDATE" $NAME
log_end_msg $?
